job('First-Job-Via-DSL'){
        description("First job generated by DSL on ${new Date()}, from a project hosted on github")
        scm{
                git("https://github.com/RamiroMM/Python_Test.git", main)
        }
        steps{
                shell("python3 test.py")
        }
        publishers{
                archiveArtifacts('**/*.html')
        }
}
